// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_spline
List cpp_spline(arma::vec y_ord, arma::vec x_ord, double lambda, int n, int n_grid);
RcppExport SEXP uniSolve_cpp_spline(SEXP y_ordSEXP, SEXP x_ordSEXP, SEXP lambdaSEXP, SEXP nSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_ord(y_ordSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_ord(x_ordSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_spline(y_ord, x_ord, lambda, n, n_grid));
    return rcpp_result_gen;
END_RCPP
}
// cpp_spline_raw
arma::vec cpp_spline_raw(arma::vec y_ord, arma::vec x_ord, double lambda, int n, int n_grid);
RcppExport SEXP uniSolve_cpp_spline_raw(SEXP y_ordSEXP, SEXP x_ordSEXP, SEXP lambdaSEXP, SEXP nSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_ord(y_ordSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_ord(x_ordSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_spline_raw(y_ord, x_ord, lambda, n, n_grid));
    return rcpp_result_gen;
END_RCPP
}
// cpp_temp_func
double cpp_temp_func(double lambda, arma::vec y_ord, arma::vec x_ord, int n, int n_grid, double lambda2);
RcppExport SEXP uniSolve_cpp_temp_func(SEXP lambdaSEXP, SEXP y_ordSEXP, SEXP x_ordSEXP, SEXP nSEXP, SEXP n_gridSEXP, SEXP lambda2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_ord(y_ordSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_ord(x_ordSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_temp_func(lambda, y_ord, x_ord, n, n_grid, lambda2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_uniroot
double cpp_uniroot(double lambda_min, double lambda_max, arma::vec y_ord, arma::vec x_ord, int n, int n_grid, double lambda2, double tol);
RcppExport SEXP uniSolve_cpp_uniroot(SEXP lambda_minSEXP, SEXP lambda_maxSEXP, SEXP y_ordSEXP, SEXP x_ordSEXP, SEXP nSEXP, SEXP n_gridSEXP, SEXP lambda2SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda_min(lambda_minSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_ord(y_ordSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_ord(x_ordSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_uniroot(lambda_min, lambda_max, y_ord, x_ord, n, n_grid, lambda2, tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_solve_prox
arma::vec cpp_solve_prox(arma::vec y_ord, arma::vec x_ord, double lambda1, double lambda2, int n, int n_grid);
RcppExport SEXP uniSolve_cpp_solve_prox(SEXP y_ordSEXP, SEXP x_ordSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP nSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_ord(y_ordSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_ord(x_ordSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_solve_prox(y_ord, x_ord, lambda1, lambda2, n, n_grid));
    return rcpp_result_gen;
END_RCPP
}
